//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteGoodsStock.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMvcStockEntities : DbContext
    {
        public DBMvcStockEntities()
            : base("name=DBMvcStockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCATEGORY> TBLCATEGORY { get; set; }
        public virtual DbSet<TBLCUSTOMER> TBLCUSTOMER { get; set; }
        public virtual DbSet<TBLPRODUCTS> TBLPRODUCTS { get; set; }
        public virtual DbSet<TBLSALES> TBLSALES { get; set; }
        public virtual DbSet<TBLSTAFF> TBLSTAFF { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
    }
}
