//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteGoodsStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSALES
    {
        public int id { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> staff { get; set; }
        public Nullable<int> customer { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual TBLCUSTOMER TBLCUSTOMER { get; set; }
        public virtual TBLPRODUCTS TBLPRODUCTS { get; set; }
        public virtual TBLSTAFF TBLSTAFF { get; set; }
    }
}
